version: "3"

services:
  mariadb:
    image: mariadb
    container_name: "database"
    ports:
      - '13306:3306'
    volumes:
      - ./mariadb-init.d:/docker-entrypoint-initdb.d
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    environment:
      TZ: "Asia/Seoul"
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ${MARIADB_PASSWORD}
    restart: always